apiVersion: smana.dev/v1alpha1
kind: Flux
metadata:
  name: flux-get-started
spec:
  git:
    url: git@github.com:Smana/flux-get-started.git
    branch: master
    path: "flux/smana-cluster"
    secretName: "flux-get-started-ssh"
  helmOperator:
    allowNamespace: "demo"
    create: true
    createCRD: false
    tillerNamespace: flux
    tls:
      verify: true
      enable: true
      hostname: tiller-deploy.smana.dev
  additionalArgs:
  - --git-sync-tag=smana-cluster
  memcached:
    enabled: false
