apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: fluxes.dailymotion.com
spec:
  group: dailymotion.com
  names:
    kind: Flux
    listKind: FluxList
    plural: fluxes
    singular: flux
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
