apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/resource-policy: keep
  labels:
    app: flux
    chart: flux-0.6.3
    heritage: Tiller
    release: flux
  name: helmreleases.flux.weave.works
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: flux.weave.works
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames:
    - hr
    singular: helmrelease
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            chart:
              oneOf:
              - properties:
                  git:
                    format: git
                    type: string
                  path:
                    type: string
                  ref:
                    type: string
                required:
                - git
                - path
              - properties:
                  chartPullSecret:
                    properties:
                      name:
                        type: string
                  name:
                    type: string
                  repository:
                    format: url
                    type: string
                  version:
                    format: semver
                    type: string
                required:
                - repository
                - name
                - version
            releaseName:
              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
              type: string
            resetValues:
              type: boolean
            timeout:
              format: int64
              type: integer
            valueFileSecrets:
              properties:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
              type: array
            values:
              type: object
          required:
          - values
          - chart
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1beta1
